### PR TITLE
Prevent altbuffer with empty name breaking results, fixes #18

### LINKED ISSUE #18: After `:tab drop file.js` into neovim from empty buffer `:FuzzyOpen` acts differently in this buffer
```
:tab drop file
```
In this buffer when you run `:FuzzyOpen` it matches on filenames in open buffers, not all the files in git. If you switch to any other buffer it will behave normally, but switch back to the "bugged" buffer and it won't work.

However if you `:tab drop` from a buffer with an open file then `:FuzzyOpen` will work fine.

Could be a bug with neovim.

### PR DESCRIPTION
**Pull request by ohjames**
Fixes #18

### CODE REVIEW

**Comment by cloudhead** [comment]
Hmm I believe the recent change https://github.com/cloudhead/neovim-fuzzy/commit/d4d1b6692cc70808dc8f440bcc6b7dc2d59288bc fixes this already by only allowing real files to be shown in the list.

**Comment by ohjames** [comment]
@cloudhead Nope, that change filters before the push I changed, check the line numbers. The related issue was tested with the most recent master.

**Comment by ohjames** [comment]
That loop only goes over the numbers buffers, the alternate buffer is not numbered.

**Comment by ohjames** [comment]
Done

**Comment by ohjames** [comment]
👍 With these 3 PRs merged I can finally ditch my own version of this plugin.

**Comment by cloudhead** [comment]
Haha great! There was another edge case with the emtpy filename I just fixed here: https://github.com/cloudhead/neovim-fuzzy/commit/8f1d0ab7cf447196b564aa64231d088e97409b23

**Pull request merged**
