### PR TITLE
Fixed: Open selected files in splits with keybindings

### PR DESCRIPTION
**Pull request by nannery**
This is a continuation of PR #34 for Issue  #15. I hadn't seen any movement so I added the fixes that @cloudhead wanted. If this isn't the place, let me know

### CODE REVIEW

**Comment by jf** [comment]
@cloudhead could you please review this? neovim-fuzzy is beautiful`^`. Now with the ability to open new files in splits, this would make this the perfect alternative to FZF!

`^` I absolutely love the fact that special thought has been given even to the case when the list of files is initially open: `When no input is given, fuzzy shows the alternate buffer (also known as '#'),
  followed by other open buffers, followed by all other files.` Beautiful, and thank you!!

**Comment by cloudhead** [comment]
Thanks @jf !

I would be interested in merging this if it didn't bind any keys. I don't think this should be the job of the plugin. It should just provide `fuzzy_split` in this case, and let the user bind keys if they wish to.

**Comment by jf** [comment]
gotcha. Would setting `g:fuzzy_bindkeys` by default to 0 do it then?

**Comment by cloudhead** [comment]
I can give it a pass in the next few days, should be fairly quick.

**Comment by jf** [comment]
hi @cloudhead , did you get time to review this?

**Comment by jf** [comment]
@cloudhead just a ping again. Do you have any issues with this PR?

**Comment by cloudhead** [comment]
Sorry to keep you hanging, and thanks!

**Pull request merged**
